services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 0d000721
    ports:
      - "172.31.241.156:3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - litebooth-network
    restart: always

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-server
    ports:
      - "172.31.241.156:9000:9000"
      - "172.31.241.156:9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 0d000721
    volumes:
      - minio_data:/data
    networks:
      - litebooth-network
    restart: always
    command: server /data --console-address ":9001"

volumes:
  mysql-data:
  minio_data:

networks:
  litebooth-network:
    driver: bridge
